### ISSUE TITLE
执行到ACTION 7: modify executable file时报错

### ISSUE THREAD

**Issue by Jakuri** [imoldman/intrude#2]
/Users/fanlining/Documents/toolchain/insert_dylib_to_binary --file /Users/fanlining/Documents/temp/Payload/ddd.app/ddd
Traceback (most recent call last):
  File "/Users/fanlining/Documents/intrude", line 197, in <module>
    main()
  File "/Users/fanlining/Documents/intrude", line 194, in main
    run(context, config)
  File "/Users/fanlining/Documents/intrude", line 177, in run
    method(context)
  File "/Users/fanlining/Documents/intrude", line 78, in do_insert_load_dylib_command_to_excutable_file
    filename = subprocess.check_output(command).strip()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, _popenargs, *_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in **init**
    errread, errwrite)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by Jakuri** [comment]
Hi imoldman,
我在使用intrude时报了以上的错误，找不到直接评论的地方，就报在这里了，请问有解决方案吗？

**Comment by imoldman** [comment]
@Jakuri  抱歉才回复，看错误提示是文件找不到，可能确实不存在，也可能是权限原因，如果想要详细的得知具体情况，我们可以邮件联系，有结果了之后再整理一下发到这里吧。
